### ISSUE TITLE
Starting issue

### ISSUE THREAD

**Issue by RobinVanCauter** [KasperFranz/pterodactyl-panel-Dockerfile#2]
When the container gets started, it gets stuck on the following:

```
Panel_1     | container initializing
Panel_1     | setting up ssl settings
Panel_1     | disabling ssl support
Panel_1     | continuing
Panel_1     |       Getting ready to start. Waiting 15 seconds for mariadb to start if you are using docker compose
Panel_1     |       env not found. Copying from example
Panel_1     |       Generating application key
Panel_1     | **************************************
Panel_1     | *     Application In Production!     *
Panel_1     | **************************************
Panel_1     | 
Panel_1     |  Do you really wish to run this command? (yes/no) [no]:
```

The artisan generate command should use --force.
After enabling this the script continues but stops again on what cache driver to use. (we should probably supply --driver parameter to the env command)

Also, did anyone actually run this container? When I run composer install inside of the comtainer, it complains about Memcached not being defined. This is fixed calling `apk add php7-memcached`

**Comment by KasperFranz** [comment]
I am using this container in production with a forced .env file since I  had so many troubles with the .env in general.

Your PR #3  Is merged, and let's hope it fixes it :)!

Thank you so much for the pullrequest

**Comment by KasperFranz** [comment]
It should be able to start now without any problems with a clear .env file :)
