### ISSUE TITLE
Unable to start service due to permissions issues

### ISSUE THREAD

**Issue by raymondhardy** [KasperFranz/pterodactyl-panel-Dockerfile#6]
I am attempting to use this and it is not starting
#HOST INFO
Docker version 1.12.6, build 78d1802
Ubuntu 16.04.3 LTS

When i use `docker-compose up -d` I get the following errors

Panel_1     |       Found env file found. continuing start
Panel_1     | 2017-08-17 18:27:07,638 CRIT Supervisor running as root (no user in config file)
Panel_1     | 2017-08-17 18:27:07,814 INFO supervisord started with pid 9
Panel_1     | 2017-08-17 18:27:08,818 INFO spawned: 'pterodactyl-worker_00' with pid 12
Panel_1     | 2017-08-17 18:27:08,821 INFO spawned: 'pterodactyl-worker_01' with pid 13
Panel_1     | 2017-08-17 18:27:08,823 INFO spawned: 'caddy' with pid 14
Panel_1     | 2017-08-17 18:27:08,824 INFO spawned: 'crond' with pid 15
Panel_1     | 2017-08-17 18:27:09,253 INFO exited: pterodactyl-worker_00 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:09,255 INFO exited: pterodactyl-worker_01 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:09,289 INFO exited: caddy (exit status 1; not expected)
Panel_1     | 2017-08-17 18:27:10,293 INFO spawned: 'pterodactyl-worker_00' with pid 41
Panel_1     | 2017-08-17 18:27:10,297 INFO spawned: 'pterodactyl-worker_01' with pid 42
Panel_1     | 2017-08-17 18:27:10,298 INFO spawned: 'caddy' with pid 43
Panel_1     | 2017-08-17 18:27:10,298 INFO success: crond entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Panel_1     | 2017-08-17 18:27:10,344 INFO exited: caddy (exit status 1; not expected)
Panel_1     | 2017-08-17 18:27:10,432 INFO exited: pterodactyl-worker_00 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:10,433 INFO exited: pterodactyl-worker_01 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:12,438 INFO spawned: 'pterodactyl-worker_00' with pid 65
Panel_1     | 2017-08-17 18:27:12,442 INFO spawned: 'pterodactyl-worker_01' with pid 66
Panel_1     | 2017-08-17 18:27:12,445 INFO spawned: 'caddy' with pid 67
Panel_1     | 2017-08-17 18:27:12,485 INFO exited: caddy (exit status 1; not expected)
Panel_1     | 2017-08-17 18:27:12,576 INFO exited: pterodactyl-worker_00 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:12,584 INFO exited: pterodactyl-worker_01 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:15,591 INFO spawned: 'pterodactyl-worker_00' with pid 89
Panel_1     | 2017-08-17 18:27:15,594 INFO spawned: 'pterodactyl-worker_01' with pid 90
Panel_1     | 2017-08-17 18:27:15,595 INFO spawned: 'caddy' with pid 91
Panel_1     | 2017-08-17 18:27:15,634 INFO exited: caddy (exit status 1; not expected)
Panel_1     | 2017-08-17 18:27:15,729 INFO gave up: caddy entered FATAL state, too many start retries too quickly
Panel_1     | 2017-08-17 18:27:15,735 INFO exited: pterodactyl-worker_00 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:15,736 INFO gave up: pterodactyl-worker_00 entered FATAL state, too many start retries too quickly
Panel_1     | 2017-08-17 18:27:15,736 INFO exited: pterodactyl-worker_01 (exit status 255; not expected)
Panel_1     | 2017-08-17 18:27:16,737 INFO gave up: pterodactyl-worker_01 entered FATAL state, too many start retries too quickly

When i connect to the container and check the worker logs i get several file cannot be opened errors like below

HP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/html/storage/logs/laravel-2017-08-17.log" could not be opened: failed to open stream: Permission denied in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /var/www/html/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Log/Writer.php(11 in /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

**Comment by KasperFranz** [comment]
not sure how this got lost.

This should be fixed in latest
